"""empty message

Revision ID: dc2f6ef198f1
Revises: 
Create Date: 2021-04-09 19:14:10.910882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2f6ef198f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('needy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('help_type', sa.String(length=200), nullable=True),
    sa.Column('home_number', sa.String(length=6), nullable=True),
    sa.Column('mobile_number', sa.String(length=12), nullable=True),
    sa.Column('relative_number', sa.String(length=12), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('key', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iin'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('addr', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=11), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_phone', sa.String(length=11), nullable=False),
    sa.Column('owner_email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('username', sa.String(length=31), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('key', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email'),
    sa.UniqueConstraint('contact_phone'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('org_name'),
    sa.UniqueConstraint('owner_email'),
    sa.UniqueConstraint('owner_phone'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('username')
    )
    op.create_table('organization_registration_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=True),
    sa.Column('used_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('username', sa.String(length=31), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('key', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('username')
    )
    op.create_table('help_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('help_type', sa.String(length=200), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('from_needy', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('completion_status', sa.Boolean(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['volunteer.id'], ),
    sa.ForeignKeyConstraint(['from_needy'], ['needy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('volunteer_org',
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], )
    )
    op.create_table('volunteer_registration_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=True),
    sa.Column('used_status', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_query_slug', sa.String(length=200), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['help_query_slug'], ['help_query.slug'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('needy_id', sa.Integer(), nullable=False),
    sa.Column('help_query_id', sa.Integer(), nullable=False),
    sa.Column('help_query_slug', sa.String(length=200), nullable=False),
    sa.Column('to_volunteer', sa.Integer(), nullable=True),
    sa.Column('from_organization', sa.Integer(), nullable=True),
    sa.Column('to_organization', sa.Integer(), nullable=True),
    sa.Column('from_volunteer', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_organization'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['from_volunteer'], ['volunteer.id'], ),
    sa.ForeignKeyConstraint(['help_query_id'], ['help_query.id'], ),
    sa.ForeignKeyConstraint(['needy_id'], ['needy.id'], ),
    sa.ForeignKeyConstraint(['to_organization'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['to_volunteer'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('needy_id', sa.Integer(), nullable=False),
    sa.Column('vol_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('help_query_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['help_query_id'], ['help_query.id'], ),
    sa.ForeignKeyConstraint(['needy_id'], ['needy.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_completion')
    op.drop_table('notification')
    op.drop_table('bookmark')
    op.drop_table('volunteer_registration_key')
    op.drop_table('volunteer_org')
    op.drop_table('help_query')
    op.drop_table('volunteer')
    op.drop_table('organization_registration_key')
    op.drop_table('organization')
    op.drop_table('needy')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
